### ISSUE TITLE
Paging issue with scrollbar

### ISSUE THREAD

**Issue by mcooper7290** [tsuoanttila/GridExtensionPack#1]
First off - great extension!  This is just what I need!

When I enable paging mode and set the page length to something like "10" Grid displays the header row + 9 rows of data from the container.  The 10th row is on the page but you must scroll down to see it.

The behavior I expect is that each page will display PageLength data rows without the scrollbar.  Perhaps GridExtensionpack is counting the header row when determining the rows to display?
![grid-paging-scrollbar](https://cloud.githubusercontent.com/assets/1441386/8362604/cc4ed2fa-1b2e-11e5-82fa-28af2114c158.PNG)

**Comment by tsuoanttila** [comment]
I need to check the Grid documentation about the height by rows, if it does not take into account any headers or footers. Might be I've overlooked some feature of it.

**Comment by mcooper7290** [comment]
I think the issue is that I also need to call:

grid.setHeightByRows(10);
grid.setHeightMode(HeightMode.ROW);

If I do this, then Grid does not show the scrollbar.  However, I do have a different issue with how Grid is painting itself when I setHeightMode(HeightMode.ROW) but that's a Grid issue I think.

I would expect, that when I PagingControls.setPageLength() that this would update Grid as well (by calling setHeightByRows() and setHeightMode() automatically).

**Comment by tsuoanttila** [comment]
I added some event magic to page changes, now it should fire event when needed.

**Comment by mcooper7290** [comment]
I just switched over to version 0.2.1 and disabled 
grid.setHeightByRows(10);
grid.setHeightMode(HeightMode.ROW);

When i disable the above in my code I still see the old behavior.  If I create the Grid, add PagedContainer and then later call PagingControls.setPageLength() the Grid display is not updated, though the values returned by PagingControls.getPageCount is the new value.

**Comment by tsuoanttila** [comment]
Did you call the new setGrid method in the PagedContainer? That is essential for the PagingControls to know which Grid to call to.

**Comment by mcooper7290** [comment]
Yes, I was not calling setGrid().  It works now!

Suggestion: Perhaps you should require a Grid instance be given to 
PagedContainer() constructor to elinate someone not knowing/forgetting?

Cheers,

mike

**Comment by tsuoanttila** [comment]
Well, then there's the issue of Grid and Container both wanting each other for their constructors.. I could make it part of PagedContainer constructor and force to use Grid setContainerDataSource method, maybe I'll add an alternative constructor with the Grid parameter.
