### ISSUE TITLE
SidebarMenuExtension: closing the sidebar after executing command

### ISSUE THREAD

**Issue by polinfo** [tsuoanttila/GridExtensionPack#15]
SidebarMenuExtension does not seem to have a simple way to close the sidebar after the custom command has been executed. 
While the ability to set it from APIs would be welcome (but it's more work), a much simpler change in the code would already go a long way in helping to customize the extension to obtain that behavior: the relevant method SidebarMenuExtensionConnector.createMenuItem() could be made protected instead of private, allowing override in a custom connector that extends SidebarMenuExtensionConnector.

Right now one must practically write a new connector and tie it with a separate extension (!) - Vaadin won't allow multiple @Connect to the same connector unless they're subclasses... plus you cannot inherit directly from SidebarMenuExtension (private constructor, static factory method!) and that means that one has to import into every project and mantain two different full source files from GridExtensionPack just because of a private method.

It would be great if you could change that single line of code (and perhaps review the addon someday and do the same with a bunch of other private-for-no-reason methods all over the code... they make using the addon needlessly harder)

**Comment by tsuoanttila** [comment]
I'll try to have the time to get this project back up to a sensible state, but unfortunately I'd need 24 extra hours to each week to keep up with everything. If you can already suggest some changes, I do accept pull requests. For example changing some privates to protected would be a really nice patch for this project.
