### ISSUE TITLE
7.6.8 and 7.7.0beta1

### ISSUE THREAD

**Issue by reggiepierce** [tsuoanttila/GridExtensionPack#17]
I've been trying to use wscdn to compile this on 7.6.8 and 7.7.0beta1. It seems to get a 500 error every time.

Is this add on broken on those versions?

Thanks.

**Comment by tsuoanttila** [comment]
Tested with 1.1.1 and Vaadin 7.7.0.beta1, CDN seems to work as expected with the vaadin-maven-plugin. Not sure if there are some issues with the earlier WSCDN plugin. Please file a new ticket if you still have issues with this.
