### ISSUE TITLE
Upgrade to Vaadin 8

### ISSUE THREAD

**Issue by srandoll** [tsuoanttila/GridExtensionPack#18]
Please upgrade you great extension to Vaadin 8.

**Comment by tsuoanttila** [comment]
Work for this is in progress. I still have to implement the replacement for PagedContainer for V8, then it should be good to go and releasable

**Comment by neerup** [comment]
Any chance this plugin can be released with or without the PagedContainer any time soon?
It would be great not having to clone and build this plugin manually..

**Comment by tsuoanttila** [comment]
2.0.0 released to Vaadin Directory, contains a PagedDataProvider to replace PagedContainer.
