### ISSUE TITLE
PagingControls#pageNumber can become -1 when the backing data provider is empty

### ISSUE THREAD

**Issue by Darsstar** [tsuoanttila/GridExtensionPack#19]
The following causes PagingControls#updatePageNumber() to be called in a state which results in the page number being -1.

````
backendProvider.refreshAll();
pagingProvider.getBackendSize();
````

I will submit a pull request in a bit. I want a issue number to mention in the commit first.

**Comment by tsuoanttila** [comment]
Fixed in #20
