### ISSUE TITLE
unsatisfiable if condition in CtrlClickSelectionHandler

### ISSUE THREAD

**Issue by yoshie82** [tsuoanttila/GridExtensionPack#31]
````java
	protected void ctrlClickSelect(SelectionModel<JsonObject> model, CellReference<JsonObject> cell,
			GridClickEvent event) {
		NativeEvent e = event.getNativeEvent();
		JsonObject row = cell.getRow();
		if (!e.getCtrlKey() && !e.getMetaKey()) {
			model.deselectAll();
		}

		if (model.isSelected(row)) { // can never be true, if all items were deselected in former if condition
			model.deselect(row);
		} else {
			model.select(row);
		}
	}
````

**Comment by tsuoanttila** [comment]
The idea of that event handler is to:
1) Add or Remove from selection if `Control` or `Meta` key is pressed.
2) Select only the clicked row if `Control` is not clicked.

Knowing how it's supposed to work, the code block above does exactly what it is supposed to.

How would you expect the control selection to work in this case?

**Comment by yoshie82** [comment]
The problem is: you can not deselect all items and 2 lines later you ask wether a row is selected.

- Select one row
- Deselect this row by clicking on it

It is not possible to deselect an selected row by clicking on it without any meta keys, because this row is deselected in the first if an reselected in the second (in the else). A solution would be to check the flag before deselecting all items.

**Comment by tsuoanttila** [comment]
The behaviour here is on purpose copied from the `Table` component in Vaadin 7. Try https://demo.vaadin.com/sampler-7.7/#ui/grids-and-trees/table for example. Changing this behaviour would make it not be the `TableSelectionModel` anymore.

**Comment by yoshie82** [comment]
But it is not the behaviour of multiselection/singleselection model for grid in vaadin 8 ^^
Expected behaviour is, that a selected row is deselected, if you click on it again. I don't want to press the ctrl key to deselect a selected row.

**Comment by tsuoanttila** [comment]
The `TableSelectionMode` is a replacement for the Vaadin 8 selection model to bring back the Vaadin 7 table selection behaviour. If you want to use the Vaadin 8 selection model, you won't need the TableSelectionModel.

**Comment by yoshie82** [comment]
How it is possible to use the ctrl/shift behaviour with vaadin 8?

Of course... you're right... it is the same behaviour....
But I think, the expected behaviour would be as described...
I'll do my own implementation.

**Comment by tsuoanttila** [comment]
I'm afraid that that functionality has been more or less overridden with the use of the selection checkbox column. You can of course always copy my code in this project and modify the kind of selection model you want for yourself. Back in the days of Vaadin 7.5 or 7.6 when I made this, a lot of users were asking for the possibility to get the Vaadin Table selection for use with Grid, and that's what is provided in this add-on. The basic blocks for custom selection can be picked from here.

**Comment by yoshie82** [comment]
We only have one senseful use case for using checkboxes instead of the meta keys...

Fortunately your methods are not private... ;)
