### ISSUE TITLE
Grid is clipped at bottom when Paging is used

### ISSUE THREAD

**Issue by mcooper7290** [tsuoanttila/GridExtensionPack#4]
When I use PagedContainer with Grid the bottom portion of the Grid is clipped (not displayed) unless I click and select and item in the table.

This screenshot shows the problem.  This is what I see when the page loads before I click on anything:

![grid-paging-enabled-1](https://cloud.githubusercontent.com/assets/1441386/8781402/9f64f5aa-2ec3-11e5-803f-34b50f20938e.PNG)

After clicking any item in the grid I see the grid properly displayed:

![grid-paging-enabled-2](https://cloud.githubusercontent.com/assets/1441386/8781422/bad6177e-2ec3-11e5-854b-88c77fdd0aee.PNG)

If I disable PagedContainer in the same Grid, it works fine.  Here is what it looks like:

![grid-paging-disabled](https://cloud.githubusercontent.com/assets/1441386/8781433/cb8d9b14-2ec3-11e5-81fe-b2e02f6eb097.PNG)

Here is a summary of my code:

<code>
Grid grid = new Grid();
PagedContainer pagedContainer = null;
pagedContainer = new PagedContainer(getJpaContainer());
pagedContainer.setGrid(grid);
grid.setContainerDataSource(pagedContainer);
</code>

The Grid resides inside of a fairly complex layout hierarchy which I cannot easily provide code for.

I'm using Vaadin 7.5.1 and GridExtensionPack 0.2.2

Vaadin debug mode -> Analyze Layout shows no problems.

**Comment by mcooper7290** [comment]
It doesn't look like this is an issue with PagedContainer.  I fixed the problem by making the parent layout 100% width and that fixed it. Still not sure why, but it doesn't look to be related to your code.

**Comment by tsuoanttila** [comment]
If you are using Vaadin 7.5.1 there was a fix to render nested invalid layouts differently.

**Comment by mcooper7290** [comment]
Yeah I saw the same problem in 7.5.0 too so it might be some other Grid issue.

**Comment by tsuoanttila** [comment]
please post a ticket with some debug info and a simple test UI to http://dev.vaadin.com so we can fix it!
