### ISSUE TITLE
ContextClickExtension instead ContextMenuExtension

### ISSUE THREAD

**Issue by isccarrasco** [tsuoanttila/GridExtensionPack#5]
In the Developer Guide and  Features, was used a references to a ContextMenuExtension class, that is not included on the add-on. Is this a redaction mistake? or the class is missing on the add-on?.

**Comment by tsuoanttila** [comment]
I think that the ContextMenuExtension was the original name, but since it was a bit misleading (as it does _not_ provide actual context menus) I renamed it at some point. Where did you find that reference? I'll update the naming if I can.

**Comment by isccarrasco** [comment]
Thanks ...

I found it when reading the documentation, trying to apply the documented example, but don't work, then i went to clone the project and review inside the code, and found that the Class is not present, and i changed the reference and then finally work perfectly.
